// UI 文案集中表（docs/word-puzzle-ui-screens.md §6）——換語言只改這個檔，不做 i18n 框架。
export const strings = {
  levelTitle: (n) => `第 ${n} 關`,
  alreadyFound: '已找到',
  levelClear: '過關！',
  nextLevel: '下一關',
  bonusFound: (n) => `額外單字 +${n}`,
  noCoins: '金幣不足',
  tutorial: '滑過字母，連成單字',
  rotateDevice: '請轉直畫面',
  allClear: '更多關卡即將推出',
  backToLevels: '關卡選擇',
  settings: '設定',
  sound: '音效',
  about: '關於',
  replayNote: '重玩不再獲得金幣',
  share: '分享',
  shareScore: '分享戰績', // 過關卡片上那顆；設定裡的仍用中性的 share
  // 字母數 3–7，用中文數字才接得上前後文；超出範圍就退回阿拉伯數字（不會讀成 undefined）。
  // 結尾的 \n 是留給 bridge.share 接上的網址，讓它與盤面之間空一行。
  shareText: (n, letters, grid) =>
    `我正在玩 Lexoria 第 ${n} 關\n\n只用 ${letters.join(' ')} ${'三四五六七'[letters.length - 3] ?? letters.length}個字母，拼出單字填滿空格\n\n${grid}\n`,
  shareCopied: '已複製，可直接貼上',
  shareFailed: '此瀏覽器無法分享',
  shareImageTitle: (n) => `Lexoria · 第 ${n} 關`,
  download: '下載圖片',
  clearWordsHint: '點單字查看解釋',
  redeemPlaceholder: '貼上兌換碼',
  redeemAction: '兌換',
  redeemInvalid: '無效的兌換碼',
  redeemExpired: '兌換碼已過期',
  redeemUsed: '此兌換碼已使用過',
  redeemBehind: '進度已超過此兌換碼的關卡',
  redeemCoins: (n) => `兌換成功，金幣 +${n}`,
  redeemLevel: (n) => `兌換成功，已解鎖至第 ${n} 關`,
  claimLabel: '領取金幣',
  claimReady: (n) => `+${n}`,
  claimSeconds: (s) => `${s} 秒`,
  claimSuccess: (n) => `已領取金幣 +${n}`,
  claimWait: (h, m) => (h > 0 ? `${h} 小時 ${m} 分後可領取金幣` : `${m} 分鐘後可領取金幣`),
  claimAlmost: '就快好了！',
  loadFailed: '關卡資料載入失敗，請檢查網路連線',
  retry: '重新載入',
};
