// UI 文案集中表（docs/word-puzzle-ui-screens.md §6）——換語言只改這個檔，不做 i18n 框架。
export const strings = {
  levelTitle: (n) => `第 ${n} 關`,
  alreadyFound: '已找到',
  levelClear: '過關！',
  nextLevel: '下一關',
  bonusFound: (n) => `額外單字 +${n}`,
  noCoins: '金幣不足',
  tutorial: '滑過字母，連成單字',
  rotateDevice: '請轉直畫面',
  allClear: '更多關卡即將推出',
  backToLevels: '關卡選擇',
  settings: '設定',
  sound: '音效',
  haptic: '震動',
  about: '關於',
  replayNote: '重玩不再獲得金幣',
  share: '分享進度',
  shareText: (n) => `我在 Lexoria 正在挑戰第 ${n} 關！`,
  shareCopied: '已複製！',
  shareImageTitle: (n) => `Lexoria · 第 ${n} 關`,
  clearWordsHint: '點單字查看解釋',
  redeemPlaceholder: '貼上兌換碼',
  redeemAction: '兌換',
  redeemInvalid: '無效的兌換碼',
  redeemExpired: '兌換碼已過期',
  redeemUsed: '此兌換碼已使用過',
  redeemBehind: '進度已超過此兌換碼的關卡',
  redeemCoins: (n) => `兌換成功，金幣 +${n}`,
  redeemLevel: (n) => `兌換成功，已解鎖至第 ${n} 關`,
  claimLabel: '領取金幣',
  claimReady: (n) => `+${n}`,
  claimSeconds: (s) => `${s} 秒`,
  claimSuccess: (n) => `已領取金幣 +${n}`,
  claimWait: (h, m) => (h > 0 ? `${h} 小時 ${m} 分後可領取金幣` : `${m} 分鐘後可領取金幣`),
  claimAlmost: '就快好了！',
  loadFailed: '關卡資料載入失敗，請檢查網路連線',
  retry: '重新載入',
};
